[analysis]
apis_llvm = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/apis_llvm.json"
apis_clang = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/apis_clang.json"
coercemap = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/coerce.log"
headers = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/exported_functions.txt"
incomplete_types = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/incomplete_types.txt"
conditions = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/conditions.json"
# minimum_apis = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/apis_minimized.txt"
# minimum_apis = "/workspaces/libfuzz/targets/cpu_features/minimal_api_2.txt"
# minimum_apis = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/apis_minimized_3.txt"
minimum_apis = ""
data_layout = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/data_layout.txt"
enum_types = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/enum_types.txt"
weights = "/workspaces/libfuzz/analysis/cpu_features/work/apipass/weights.json"


[generator]
workdir = "/workspaces/libfuzz/workdir/cpu_features"
policy = "constraint_based"
dep_graph = "type"
# dep_graph = "undef"
pool_size = 40
driver_size = 10
num_seeds = 1
backend = "libfuzz"

[backend]
headers = "/workspaces/libfuzz/analysis/cpu_features/work/include/"
public_headers = "/workspaces/libfuzz/targets/cpu_features/public_headers.txt"
