[analysis]
apis_llvm = "/workspaces/libfuzz/analysis/libtiff/work/apipass/apis_llvm.json"
apis_clang = "/workspaces/libfuzz/analysis/libtiff/work/apipass/apis_clang.json"
coercemap = "/workspaces/libfuzz/analysis/libtiff/work/apipass/coerce.log"
headers = "/workspaces/libfuzz/analysis/libtiff/work/apipass/exported_functions.txt"
incomplete_types = "/workspaces/libfuzz/analysis/libtiff/work/apipass/incomplete_types.txt"
conditions = "/workspaces/libfuzz/condition_extractor/conditions-tmp-icpt2.json"
minimum_apis = "/workspaces/libfuzz/analysis/libtiff/work/apipass/apis_minimized.txt"
# minimum_apis = "/workspaces/libfuzz/analysis/libtiff/work/apipass/apis_minimized_2.txt"
# minimum_apis = ""
data_layout = "/workspaces/libfuzz/analysis/libtiff/work/apipass/data_layout.txt"


[generator]
workdir = "/workspaces/libfuzz/workdir/libtiff"
policy = "constraint_based"
dep_graph = "type"
# dep_graph = "undef"
pool_size = 5
driver_size = 10
num_seeds = 1
backend = "libfuzz"

[backend]
headers = "/workspaces/libfuzz/analysis/libtiff/work/include/"
