[analysis]
apis_llvm = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/apis_llvm.json"
apis_clang = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/apis_clang.json"
coercemap = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/coerce.log"
headers = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/exported_functions.txt"
incomplete_types = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/incomplete_types.txt"
conditions = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/conditions.json"
minimum_apis = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/apis_minimized.txt"
# minimum_apis = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/apis_minimized_2.txt"
# minimum_apis = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/apis_minimized_3.txt"
# minimum_apis = ""
data_layout = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/data_layout.txt"
enum_types = "/workspaces/libfuzz/analysis/cpuinfo/work/apipass/enum_types.txt"


[generator]
workdir = "/workspaces/libfuzz/workdir/cpuinfo"
policy = "constraint_based"
dep_graph = "type"
# dep_graph = "undef"
pool_size = 1
driver_size = 10
num_seeds = 1
backend = "libfuzz"

[backend]
headers = "/workspaces/libfuzz/analysis/cpuinfo/work/include/"
public_headers = "/workspaces/libfuzz/targets/cpuinfo/public_headers.txt"
