[analysis]
apis_llvm = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/apis_llvm.json"
apis_clang = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/apis_clang.json"
coercemap = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/coerce.log"
headers = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/exported_functions.txt"
incomplete_types = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/incomplete_types.txt"
conditions = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/conditions.json"
# minimum_apis = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/apis_minimized.txt"
# minimum_apis = "/workspaces/libfuzz/targets/libsndfile/custom_apis_minized.txt"
# minimum_apis = "/workspaces/libfuzz/targets/libsndfile/apis_minimized.txt"
minimum_apis = ""
# minimum_apis = "/workspaces/libfuzz/targets/libsndfile/min_api.txt"
data_layout = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/data_layout.txt"
enum_types = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/enum_types.txt"
weights = "/workspaces/libfuzz/analysis/libsndfile/work/apipass/weights.json"


[generator]
workdir = "/workspaces/libfuzz/workdir/libsndfile"
policy = "constraint_based"
dep_graph = "type"
# dep_graph = "undef"
pool_size = 10
driver_size = 20
num_seeds = 1
backend = "libfuzz"

[backend]
headers = "/workspaces/libfuzz/analysis/libsndfile/work/include/"
public_headers = "/workspaces/libfuzz/targets/libsndfile/public_headers.txt"
